### ISSUE TITLE
Создание единого `пула` для всех запросов

### ISSUE THREAD

**Issue by Ar4ikov** [Ar4ikov/vk_advanced_api#1]
Доброй ночи!

Пришла в голову следующая мысль: 
`Хм, а почему бы не сделать единый пул запросов, поскольку в апи есть как минимум 2 потока, которые работают в разнобой и постоянно подают запросы к API?` 

Сейчас в ветви `Testing` уже введена данная возможность. Теперь каждый запрос будет уходить в пул, и время отклика составит 0.34 секунды для каждого запроса, так что задержки в коде уже ваших скриптов будут бесполезны.

Нужно ли было делать данную фичу или она бесполезна ?(кхмхм, `Notifications Events` постоянно делает запросы к API -> notifications.get(), поэтому пул необходим для этой функции (Теперь её нужно подрубать вручную, в `examples/polling.py` уже описано, как)

**Comment by madvil2** [comment]
Отличная идея! Жаль что твои родители не чайлдфри
